# Generated by Django 3.1.6 on 2021-02-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='comment',
            field=models.TextField(default='asdf'),
            preserve_default=False,
        ),
    ]
