# Generated by Django 3.1.6 on 2021-02-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='question_text',
            new_name='u_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pub_date',
        ),
    ]
