# Generated by Django 3.1.6 on 2021-02-04 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('from_user', 'to_user')},
        ),
    ]
