# Generated by Django 3.1.6 on 2021-02-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='e', upload_to=''),
            preserve_default=False,
        ),
    ]
