# Generated by Django 3.1.6 on 2021-02-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
    ]
