# Generated by Django 3.1.6 on 2021-02-05 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210205_0553'),
        ('user', '0006_auto_20210205_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_product', to='main.product'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('from_user', 'product')},
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_from_user', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_product', to='main.product')),
            ],
        ),
    ]
