# Generated by Django 3.1.6 on 2021-02-05 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210205_0553'),
        ('user', '0007_auto_20210205_0642'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('from_user', 'product')},
        ),
    ]
