# Generated by Django 3.1.6 on 2021-02-04 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('from_user',)},
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='to_user',
        ),
    ]
