# Generated by Django 3.1.6 on 2021-02-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_report_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='message',
            new_name='content',
        ),
    ]
