# Generated by Django 3.1.6 on 2021-02-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_category', models.CharField(max_length=200)),
                ('p_name', models.CharField(max_length=200)),
                ('p_price', models.CharField(max_length=200)),
                ('p_content', models.CharField(max_length=200)),
                ('p_nego', models.CharField(max_length=200)),
                ('p_tag', models.CharField(max_length=200)),
                ('p_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
