# Generated by Django 3.1.6 on 2021-02-04 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='live시작시간')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_category', models.CharField(max_length=200)),
                ('p_name', models.CharField(max_length=32, verbose_name='상품제목')),
                ('p_price', models.IntegerField(default=0, verbose_name='상품가격')),
                ('p_content', models.CharField(max_length=32, verbose_name='상품설명')),
                ('p_image', models.ImageField(null=True, upload_to='', verbose_name='대표사진')),
                ('p_tag', models.CharField(max_length=200)),
                ('p_nego', models.BooleanField()),
                ('p_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록날짜')),
                ('p_likecount', models.IntegerField(default=0, null=True, verbose_name='좋아요수')),
                ('p_live', models.CharField(default='', max_length=200, verbose_name='라이브방송여부')),
            ],
        ),
    ]
