# Generated by Django 3.1.6 on 2021-02-04 11:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='대표사진'),
        ),
        migrations.AddField(
            model_name='product',
            name='p_likecount',
            field=models.IntegerField(default=0, null=True, verbose_name='좋아요수'),
        ),
        migrations.AddField(
            model_name='product',
            name='p_live',
            field=models.CharField(default='', max_length=200, verbose_name='라이브방송여부'),
        ),
        migrations.AddField(
            model_name='product',
            name='p_seller',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_content',
            field=models.CharField(max_length=32, verbose_name='상품설명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록날짜'),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_name',
            field=models.CharField(max_length=32, verbose_name='상품제목'),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_nego',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_price',
            field=models.IntegerField(default=0, verbose_name='상품가격'),
        ),
        migrations.CreateModel(
            name='LiveProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='live시작시간')),
                ('l_product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
