# Generated by Django 3.1.6 on 2021-02-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210205_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveproduct',
            name='l_sprice',
            field=models.IntegerField(default=0, verbose_name='라이브 시작가격'),
        ),
        migrations.AddField(
            model_name='product',
            name='p_viewcount',
            field=models.IntegerField(default=0, null=True, verbose_name='조회수'),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_image',
            field=models.ImageField(upload_to='', verbose_name='대표사진'),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_live',
            field=models.CharField(default=0, max_length=200, verbose_name='라이브방송여부'),
        ),
    ]
