# Generated by Django 3.1.6 on 2021-02-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210205_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_viewcount',
            field=models.IntegerField(default=0, null=True, verbose_name='조회수'),
        ),
    ]
