# Generated by Django 3.1.6 on 2021-02-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_p_viewcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_live',
            field=models.CharField(default=0, max_length=200, verbose_name='라이브방송여부'),
        ),
    ]
