# Generated by Django 3.1.6 on 2021-02-05 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210205_1211'),
        ('main', '0003_auto_20210205_0553'),
    ]

    operations = [
    ]
