# Generated by Django 3.1.6 on 2021-02-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_merge_20210205_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_buy',
            field=models.BooleanField(default=False, verbose_name='판매완료여부'),
        ),
    ]
