# Generated by Django 3.1.6 on 2021-02-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_p_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_content',
            field=models.CharField(max_length=200, verbose_name='상품설명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_name',
            field=models.CharField(max_length=20, verbose_name='상품제목'),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_tag',
            field=models.CharField(max_length=20),
        ),
    ]
